apiVersion: v1
kind: Service
metadata:
  namespace: kosalprime
  name: admin-api-svc
spec:
  selector:
    app: admin-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kosalprime
  name: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
      - name: admin-api
        image: 480804283544.dkr.ecr.ap-south-1.amazonaws.com/admin-api:v26
        imagePullPolicy: Always
        ports:
        - name: admin-api
          containerPort: 80
        resources: 
          requests: 
            cpu: 150m
            memory: 150Mi
          limits:
            cpu: 300m
            memory: 300Mi
